export const GET_SKIN_PAGE_DOTKEY_REQUEST = 'GET_SKIN_PAGE_DOTKEY_REQUEST';
export const GET_SKIN_PAGE_DOTKEY_SUCCESS = 'GET_SKIN_PAGE_DOTKEY_SUCCESS';
export const GET_SKIN_PAGE_DOTKEY_FAILURE = 'GET_SKIN_PAGE_DOTKEY_FAILURE';