export const GET_SKIN_PAGE_DOTKEY_REQUEST = 'GET_SKIN_PAGE_DOTKEY_REQUEST';
export const GET_SKIN_PAGE_DOTKEY_SUCCESS = 'GET_SKIN_PAGE_DOTKEY_SUCCESS';
export const GET_SKIN_PAGE_DOTKEY_FAILURE = 'GET_SKIN_PAGE_DOTKEY_FAILURE';

export const GET_DOTKEY_SINGLE_REQUEST = 'GET_DOTKEY_SINGLE_REQUEST';
export const GET_DOTKEY_SINGLE_SUCCESS = 'GET_DOTKEY_SINGLE_SUCCESS';
export const GET_DOTKEY_SINGLE_FAILURE = 'GET_DOTKEY_SINGLE_FAILURE';

export const SKIN_LOREAL_PAGE_GET_REQUEST = 'SKIN_LOREAL_PAGE_GET_REQUEST';
export const SKIN_LOREAL_PAGE_GET_SUCCESS = 'SKIN_LOREAL_PAGE_GET_SUCCESS';
export const SKIN_LOREAL_PAGE_GET_FAILURE = 'SKIN_LOREAL_PAGE_GET_FAILURE';


export const LOREAL_GET_SINGLE_DATA_REQUEST = 'LOREAL_GET_SINGLE_DATA_REQUEST';
export const LOREAL_GET_SINGLE_DATA_SUCCESS = 'LOREAL_GET_SINGLE_DATA_SUCCESS';
export const LOREAL_GET_SINGLE_DATA_FAILURE = 'LOREAL_GET_SINGLE_DATA_FAILURE';

export const GET_ESTEE_PAGE_DATA_REQUEST = 'GET_ESTEE_PAGE_DATA_REQUEST';
export const GET_ESTEE_PAGE_DATA_SUCCESS = 'GET_ESTEE_PAGE_DATA_SUCCESS';
export const GET_ESTEE_PAGE_DATA_FAILURE = 'GET_ESTEE_PAGE_DATA_FAILURE';

export const GET_ESTEE_SINGLE_REQUEST = 'GET_ESTEE_SINGLE_REQUEST';
export const GET_ESTEE_SINGLE_SUCCESS = 'GET_ESTEE_SINGLE_SUCCESS';
export const GET_ESTEE_SINGLE_FAILURE = 'GET_ESTEE_SINGLE_FAILURE';

export const GET_RAS_PAGE_DATA_REQUEST = 'GET_RAS_PAGE_DATA_REQUEST';
export const GET_RAS_PAGE_DATA_SUCCESS = 'GET_RAS_PAGE_DATA_SUCCESS';
export const GET_RAS_PAGE_DATA_FAILURE = 'GET_RAS_PAGE_DATA_FAILURE';

export const GET_RAS_SINGLE_REQUEST  = 'GET_RAS_SINGLE_REQUEST';
export const GET_RAS_SINGLE_SUCCESS  = 'GET_RAS_SINGLE_SUCCESS';
export const GET_RAS_SINGLE_FAILURE  = 'GET_RAS_SINGLE_FAILURE';

export const GET_MENS_GARNIER_PAGE_REQUEST = 'GET_MENS_GARNIER_PAGE_REQUEST';
export const GET_MENS_GARNIER_PAGE_SUCCESS = 'GET_MENS_GARNIER_PAGE_SUCCESS';
export const GET_MENS_GARNIER_PAGE_FAILURE = 'GET_MENS_GARNIER_PAGE_FAILURE';

export const GET_MENS_GARNIER_SINGLE_PAGE_REQUEST = 'GET_MENS_GARNIER_SINGLE_PAGE_REQUEST';
export const GET_MENS_GARNIER_SINGLE_PAGE_SUCCESS = 'GET_MENS_GARNIER_SINGLE_PAGE_SUCCESS';
export const GET_MENS_GARNIER_SINGLE_PAGE_FAILURE = 'GET_MENS_GARNIER_SINGLE_PAGE_FAILURE';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const GET_HAIR_DATA_REQUEST = "GET_HAIR_DATA_REQUEST";
export const GET_HAIR_DATA_SUCCESS = "GET_HAIR_DATA_SUCCESS";
export const GET_HAIR_DATA_FAILURE = "GET_HAIR_DATA_FAILURE";

export const GET_SINGAL_HAIR_DATA_REQUEST = "GET_SINGAL_HAIR_DATA_REQUEST";
export const GET_SINGAL_HAIR_DATA_SUCCESS = "GET_SINGAL_HAIR_DATA_SUCCESS";
export const GET_SINGAL_HAIR_DATA_FAILURE = "GET_SINGAL_HAIR_DATA_FAILURE";
