export const GET_SKIN_PAGE_DOTKEY_REQUEST = 'GET_SKIN_PAGE_DOTKEY_REQUEST';
export const GET_SKIN_PAGE_DOTKEY_SUCCESS = 'GET_SKIN_PAGE_DOTKEY_SUCCESS';
export const GET_SKIN_PAGE_DOTKEY_FAILURE = 'GET_SKIN_PAGE_DOTKEY_FAILURE';

export const GET_DOTKEY_SINGLE_REQUEST = 'GET_DOTKEY_SINGLE_REQUEST';
export const GET_DOTKEY_SINGLE_SUCCESS = 'GET_DOTKEY_SINGLE_SUCCESS';
export const GET_DOTKEY_SINGLE_FAILURE = 'GET_DOTKEY_SINGLE_FAILURE';

export const SKIN_LOREAL_PAGE_GET_REQUEST = 'SKIN_LOREAL_PAGE_GET_REQUEST';
export const SKIN_LOREAL_PAGE_GET_SUCCESS = 'SKIN_LOREAL_PAGE_GET_SUCCESS';
export const SKIN_LOREAL_PAGE_GET_FAILURE = 'SKIN_LOREAL_PAGE_GET_FAILURE';


export const LOREAL_GET_SINGLE_DATA_REQUEST = 'LOREAL_GET_SINGLE_DATA_REQUEST';
export const LOREAL_GET_SINGLE_DATA_SUCCESS = 'LOREAL_GET_SINGLE_DATA_SUCCESS';
export const LOREAL_GET_SINGLE_DATA_FAILURE = 'LOREAL_GET_SINGLE_DATA_FAILURE';